# Generated by Django 4.1 on 2022-10-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('doc_spec', models.TextField()),
                ('doc_image', models.ImageField(upload_to='doctors/')),
                ('d_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
